kind: ConfigMap
apiVersion: v1
metadata:
  # Must match the 'spring.application.name' property of the application
  name: camel-config
data:
  application.properties: |
    # Override the configuration properties here
    amq.host=broker-amq-amqp
    amq.queueName=incomingOrdersOCP