:scrollbar:
:data-uri:
:scrollbar:
:noaudio:

== Custom Steps

* Certain client requirements require extensions to applications
* Developers create a Apache Camel-based project, with additional metadata
* Implement a custom step using this Camel-based project
* An extension can
** consist of multiple steps
** be implemented as a Java bean or as a Camel route
* A step is aware of data types
* Supported in JBoss Fuse Tooling (JBDS 11.2+)

ifdef::showscript[]

=== Transcript

Certain requirements require extensions to applications using either Java or Apache Camel routes.
Developers can contribute native extensions to Ignite in the form of custom steps.
These steps can be invoked from an integration flow.
First, create a Apache Camel-based project with additional metadata.
Next implement the custom step using this project.
Multiple steps allowed per extension and each extension can be implemented as a Java bean or Camel Route.
Each step is data type-aware and has JBoss Fuse Tooling support, in JBoss Developer Studio 11.2 and above.

endif::showscript[]
