:scrollbar:
:data-uri:
:scrollbar:
:noaudio:

== Topics

* Design of an Integration
* Lifecycle Management of Integrations
* Packaged Connectors

ifdef::showscript[]

=== Transcript

This module covered the design and lifecycle management of Integrations, as well as packaged connectors used in Integrations

====

Planning integrations
Some planning so that you have answers to the following questions is helpful before you create an integration.

To start the integration:

Which application should the integration obtain data from?

In that application, what triggers the action that obtains the data? For example, an integration that starts by obtaining data from Twitter might trigger on a Twitter mention.

What are the data fields of interest?

What credentials does Ignite use to access this application?

To finish the integration:

Which application receives the data?

In that application, what action does the integration perform?

What are the data fields of interest?

What credentials does Ignite use to access this application?

In between the start and finish applications:

Do you need to access any other applications? For any other applications the integration accesses:

Which application does the integration need to connect to?

What action should the integration perform?

What are the data fields of interest?

What credentials should the integration use to connect to this application?

Between connections, does the integration need to operate on the data? For example:

Should the integration filter the data it operates on?

Do field names differ between source and target applications? If they do then data mapping is required.

Does the integration need to operate on the data in some customized way?

=== Workflow for creating an integration

After you log in to the Ignite console, the general steps for integrating applications are:

For each application that you want to integrate and that uses the OAuth protocol, register Ignite as a client of that application.

For each application you want to integrate, create a connection.

endif::showscript[]
